apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - "1"
            - "2"
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: pickthis
            operator: In
            values:
            - "1" 
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
  nodeName: kind-worker3
